apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: landiq-ingress
  namespace: landiq
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/rate-limit-window: "1m"
spec:
  tls:
    - hosts:
        - landiq.in
        - api.landiq.in
      secretName: landiq-tls
  rules:
    - host: landiq.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: landiq-frontend-service
                port:
                  number: 80
    - host: api.landiq.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: landiq-backend-service
                port:
                  number: 5000
