"""initial schema

Revision ID: b6117319ce29
Revises: 
Create Date: 2026-04-12 19:56:29.488607
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'b6117319ce29'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'analyst', 'admin', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('land_parcels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('survey_number', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('land_type', sa.Enum('residential', 'agricultural', 'commercial', 'industrial', name='landtype'), nullable=False),
    sa.Column('area_sqft', sa.Float(), nullable=False),
    sa.Column('quoted_price', sa.Float(), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=False),
    sa.Column('num_ownership_changes', sa.Integer(), nullable=False),
    sa.Column('last_transfer_year', sa.Integer(), nullable=True),
    sa.Column('dist_highway_km', sa.Float(), nullable=True),
    sa.Column('dist_metro_km', sa.Float(), nullable=True),
    sa.Column('near_tech_park', sa.Boolean(), nullable=False),
    sa.Column('flood_zone_risk', sa.Enum('low', 'moderate', 'high', name='floodzonerisk'), nullable=False),
    sa.Column('pending_litigations', sa.Enum('none', 'one', 'multiple', 'court_review', name='pendinglitigations'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_land_parcels_survey_number'), 'land_parcels', ['survey_number'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parcel_id', sa.String(length=36), nullable=False),
    sa.Column('doc_type', sa.Enum('sale_deed', 'ec', 'khata', 'rtc', 'other', name='doctype'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('extracted_owner', sa.String(length=255), nullable=True),
    sa.Column('extracted_area', sa.Float(), nullable=True),
    sa.Column('extracted_date', sa.String(length=50), nullable=True),
    sa.Column('integrity_score', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('verified', 'review', 'missing', name='docstatus'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['land_parcels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ownership_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parcel_id', sa.String(length=36), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=True),
    sa.Column('transfer_price', sa.Float(), nullable=True),
    sa.Column('document_ref', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['land_parcels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('parcel_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('estimated_value', sa.Float(), nullable=False),
    sa.Column('confidence_interval', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='risklevel'), nullable=False),
    sa.Column('fraud_probability', sa.Float(), nullable=False),
    sa.Column('investment_score', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.Enum('buy', 'hold', 'avoid', name='recommendation'), nullable=False),
    sa.Column('shap_values', sa.JSON(), nullable=True),
    sa.Column('forecast_1yr', sa.Float(), nullable=True),
    sa.Column('forecast_3yr', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['land_parcels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction_results')
    op.drop_table('ownership_history')
    op.drop_table('documents')
    op.drop_index(op.f('ix_land_parcels_survey_number'), table_name='land_parcels')
    op.drop_table('land_parcels')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
